version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    init: true
    restart: unless-stopped
    container_name: ${CONTAINER_NAME:-minio}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-dummy-user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-dummy-password}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME:-us-east-1}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - minio-net

volumes:
  minio_data:

networks:
  minio-net:
    driver: bridge
